version: "3.8"
services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: micronaut
      POSTGRES_PASSWORD: password
    ports:
      - "5469:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: